#!/bin/bash

### CHECK IF FILE HAS BEEN COMPILED
if [ ! -e ../shortest-path ]
then
	echo -e '\E[1;31m'"\033[1m>>>>>> You do know that the program hasn't been compiled yet, do you? <<<<<<\033[0m"
	echo -e '\E[1;31m'"\033[1m>>>>>> Please run either 'make all', 'make debug' or 'make gprof'     <<<<<<\033[0m"
	exit 1 
fi

## check command line args
# quiet flag
if [[ "$*" =~ "-q" ]]; then quiet="true"; fi

# username
user=$1

# run tests
for test in input-*
do
	# ignore folders that begin with "input-"
	if [ ! -f $test ]; then continue; fi

	# get the name of the test
	testName=${test#input-}

	## id is appended to name of logfiles to identify test runs
	sha=`git rev-parse HEAD`
	sha=${sha:0:7}
	# id ==  1st 7 chars from SHA1 of current commit + name of test + user name
	id=${sha:0:7}-$testName-$user
	# current date, prepended to id for gmon.out files
	now=`date +"%02d_%02m_%G-%T"`

	# print status
	printf "> %-50s" input-$testName

	# RUN TEST
	../shortest-path "$id" <"input-$testName" >"output-$testName"
	# store return code
	retCode=$?

	# rename gmon.out file if present
	if [ -f gmon.out ]; then mv gmon.out `date +"logs/gmon.out-$now-$id"`; fi

	# print if test passed or failed
	if [ $retCode -eq 0 ]
	then
		printf "PASSED\n"
	else
		printf "FAILED\n"
	fi
done

#### check test files against ertls files
# run tests
../shortest-path "ertl-test" <"input-ref-littleendian"   | diff -u - xoutput-ref   >diff-ref
../shortest-path "ertl-test" <"input-bench-littleendian" | diff -u - xoutput-bench >diff-bench

# diffs should be empty
if [ -s diff-ref   ]; then echo -e '\E[1;31m'"\033[1m OUTPUT FROM input-ref-littlendian differs from ertls!   \033[0m"; cat diff-ref;   fi
if [ -s diff-bench ]; then echo -e '\E[1;31m'"\033[1m OUTPUT FROM input-bench-littlendian differs from ertls! \033[0m"; cat diff-bench; fi

# clean up useless test files
rm -f logs/*-ertl-test gmon.out diff-ref diff-bench


